# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Wed Jan 18 17:29:02 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(774, 568)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(774, 568))
        MainWindow.setMaximumSize(QtCore.QSize(774, 568))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 773, 57))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.highEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.highEdit.setReadOnly(True)
        self.highEdit.setObjectName(_fromUtf8("highEdit"))
        self.gridLayout.addWidget(self.highEdit, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.lowEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lowEdit.setReadOnly(True)
        self.lowEdit.setObjectName(_fromUtf8("lowEdit"))
        self.gridLayout.addWidget(self.lowEdit, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.lastEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lastEdit.setReadOnly(True)
        self.lastEdit.setObjectName(_fromUtf8("lastEdit"))
        self.gridLayout.addWidget(self.lastEdit, 0, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.buyEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.buyEdit.setReadOnly(True)
        self.buyEdit.setObjectName(_fromUtf8("buyEdit"))
        self.gridLayout.addWidget(self.buyEdit, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 5, 1, 1)
        self.averageEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.averageEdit.setReadOnly(True)
        self.averageEdit.setObjectName(_fromUtf8("averageEdit"))
        self.gridLayout.addWidget(self.averageEdit, 2, 6, 1, 1)
        self.sellEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.sellEdit.setReadOnly(True)
        self.sellEdit.setObjectName(_fromUtf8("sellEdit"))
        self.gridLayout.addWidget(self.sellEdit, 2, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 7, 1, 1)
        self.vwapEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.vwapEdit.setReadOnly(True)
        self.vwapEdit.setObjectName(_fromUtf8("vwapEdit"))
        self.gridLayout.addWidget(self.vwapEdit, 0, 8, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 7, 1, 1)
        self.volumeEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.volumeEdit.setReadOnly(True)
        self.volumeEdit.setObjectName(_fromUtf8("volumeEdit"))
        self.gridLayout.addWidget(self.volumeEdit, 2, 8, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 60, 771, 491))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tradeList = QtGui.QTreeWidget(self.layoutWidget)
        self.tradeList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tradeList.setObjectName(_fromUtf8("tradeList"))
        self.gridLayout_2.addWidget(self.tradeList, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.depthList = QtGui.QTreeWidget(self.layoutWidget)
        self.depthList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.depthList.setObjectName(_fromUtf8("depthList"))
        self.gridLayout_3.addWidget(self.depthList, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.messageList = QtGui.QTreeWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageList.sizePolicy().hasHeightForWidth())
        self.messageList.setSizePolicy(sizePolicy)
        self.messageList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.messageList.setAutoScrollMargin(0)
        self.messageList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.messageList.setObjectName(_fromUtf8("messageList"))
        self.gridLayout_4.addWidget(self.messageList, 1, 0, 1, 2)
        self.commandEdit = QtGui.QLineEdit(self.layoutWidget)
        self.commandEdit.setObjectName(_fromUtf8("commandEdit"))
        self.gridLayout_4.addWidget(self.commandEdit, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionFull_Update = QtGui.QAction(MainWindow)
        self.actionFull_Update.setObjectName(_fromUtf8("actionFull_Update"))
        self.actionClear_Messages = QtGui.QAction(MainWindow)
        self.actionClear_Messages.setObjectName(_fromUtf8("actionClear_Messages"))
        self.menuFile.addAction(self.actionFull_Update)
        self.menuFile.addAction(self.actionClear_Messages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label.setBuddy(self.highEdit)
        self.label_2.setBuddy(self.lowEdit)
        self.label_3.setBuddy(self.lastEdit)
        self.label_4.setBuddy(self.buyEdit)
        self.label_5.setBuddy(self.sellEdit)
        self.label_6.setBuddy(self.averageEdit)
        self.label_7.setBuddy(self.vwapEdit)
        self.label_8.setBuddy(self.volumeEdit)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Mt.Gox", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "High:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Low:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Last:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Buy:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Sell:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Average:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "VWAP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Volume:", None, QtGui.QApplication.UnicodeUTF8))
        self.tradeList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tradeList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.tradeList.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Trades", None, QtGui.QApplication.UnicodeUTF8))
        self.depthList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.depthList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.depthList.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.messageList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.messageList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Message", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Update.setText(QtGui.QApplication.translate("MainWindow", "Full Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Messages.setText(QtGui.QApplication.translate("MainWindow", "Clear Messages", None, QtGui.QApplication.UnicodeUTF8))

